name: docs
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.12
  - sphinx>=4
  - sphinx-book-theme>=1.0.0
  - myst-nb
  - sphinxcontrib-bibtex
  - sphinx-autodoc-typehints
  - ipykernel
  - ipython
  - sphinx-copybutton
  - sphinx-autosummary-accessors
  - sphinxcontrib-napoleon
  - pdf2image
  - sphinx-design
  - pip
  - pip:
      - sphinxemoji
